# Generated by Django 6.0.3 on 2026-03-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')]),
        ),
    ]
